"""
Live Demo — annotated video player for the bundled sample.

Renders the sample video with bboxes, track IDs, and zone overlays baked
into the frames. No live inference runs on Streamlit Cloud's free tier;
this page is meant to show the *output* of the pipeline, not re-run it.

(The same visual would be produced by running `pipeline.run_pipeline` on
an uploaded video — see the methodology page for how to do that locally.)
"""

import json
from pathlib import Path

import cv2
import numpy as np
import pandas as pd
import streamlit as st

import pipeline


HERE = Path(__file__).parent.parent
ASSETS = HERE / "assets"


st.set_page_config(page_title="Live Demo · Retail Analytics", page_icon="🎥", layout="wide")


@st.cache_data
def load_sample_results():
    path = ASSETS / "mall_sample_results.json"
    if not path.exists():
        return None
    with open(path) as f:
        return pipeline.result_from_jsonable(json.load(f))


@st.cache_data
def load_annotated_video():
    """Pre-rendered annotated mp4. Generated by scripts/build_sample_assets.py."""
    path = ASSETS / "mall_sample_annotated.mp4"
    if not path.exists():
        return None
    with open(path, "rb") as f:
        return f.read()


@st.cache_data
def get_frames_for_video(annotated_bytes: bytes, n: int = 6):
    """Sample n evenly-spaced frames from the annotated mp4 for static preview."""
    if annotated_bytes is None:
        return []
    # Write to a tempfile so cv2 can read it
    import tempfile, os
    with tempfile.NamedTemporaryFile(suffix=".mp4", delete=False) as t:
        t.write(annotated_bytes)
        tmp = t.name
    cap = cv2.VideoCapture(tmp)
    total = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    idxs = np.linspace(0, max(total - 1, 0), n, dtype=int)
    out = []
    for idx in idxs:
        cap.set(cv2.CAP_PROP_POS_FRAMES, int(idx))
        ok, fr = cap.read()
        if ok:
            out.append(cv2.cvtColor(fr, cv2.COLOR_BGR2RGB))
    cap.release()
    os.unlink(tmp)
    return out


result = load_sample_results()
video_bytes = load_annotated_video()


st.title("🎥 Live Demo")
st.caption("Watch the computer-vision pipeline in action on the bundled sample video.")


if video_bytes is None:
    st.warning(
        "Annotated video not found in `assets/`. "
        "Run `python scripts/build_sample_assets.py` to generate it, then refresh."
    )
    st.stop()


# -----------------------------------------------------------------------------
# Player
# -----------------------------------------------------------------------------
st.subheader("Annotated playback")
st.caption(
    "Each tracked person has a persistent ID. Colored polygons are the "
    "journey + display zones. Same data the dashboard is built on."
)
st.video(video_bytes)


# -----------------------------------------------------------------------------
# Sample frames
# -----------------------------------------------------------------------------
st.subheader("Sample frames")
st.caption("Six evenly-spaced frames from the annotated video.")
frames = get_frames_for_video(video_bytes, n=6)
if frames:
    cols = st.columns(3)
    for i, fr in enumerate(frames):
        cols[i % 3].image(fr, use_container_width=True)


# -----------------------------------------------------------------------------
# What's happening in each frame
# -----------------------------------------------------------------------------
if result is not None and len(result.tracks_df):
    st.markdown("---")
    st.subheader("📍 What was detected in each frame?")

    n_per_frame = result.tracks_df.groupby("frame").size().reset_index(name="detections")
    n_per_frame["people"] = result.tracks_df.groupby("frame")["track_id"].nunique().values
    n_per_frame["time_s"] = (n_per_frame["frame"] / result.fps).round(1)

    st.line_chart(
        n_per_frame.rename(columns={"frame": "frame_idx"}).set_index("frame_idx")[["detections", "people"]],
        height=280,
    )
    st.caption(
        f"Across {result.n_frames_processed} frames at {result.fps} fps, "
        f"the detector saw an average of "
        f"{n_per_frame['detections'].mean():.1f} detections / frame "
        f"and the tracker maintained an average of "
        f"{n_per_frame['people'].mean():.1f} unique IDs / frame."
    )
